---

- hosts: localhost
  gather_facts: true
  connection: local
  tasks:

    - name: Valida existencia de Stack
      shell: "echo algo"
      
    - name: Display all variables/facts known for a host
      debug:
        var: hostvars[inventory_hostname]
      tags: debug_info
